# alembic/script.py.mako
"""add host profiles table

Revision ID: 0a79e334c3bb
Revises: 
Create Date: 2025-02-02 21:32:32.732972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a79e334c3bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    op.drop_column('users', 'last_stats_update')
    op.drop_column('users', 'twitter_url')
    op.drop_column('users', 'discord_url')
    op.drop_column('users', 'host_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('host_profile', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('discord_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('twitter_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_stats_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###