# alembic/script.py.mako
"""add timestamp fields to user model

Revision ID: 2748ce4b2e4a
Revises: ee5a6df92089
Create Date: 2025-01-28 12:14:26.600527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2748ce4b2e4a'
down_revision = 'ee5a6df92089'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'HOST', 'SUPER_ADMIN', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'HOST', 'SUPER_ADMIN', name='userrole'),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###