"""initial migration but adding 2 tables

Revision ID: 35d77a76c071
Revises: f2de8a97a6db
Create Date: 2024-12-16 12:36:57.292266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d77a76c071'
down_revision: Union[str, None] = 'f2de8a97a6db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('twitter_handle', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_rankings_id'), 'player_rankings', ['id'], unique=False)
    op.create_index(op.f('ix_player_rankings_player_name'), 'player_rankings', ['player_name'], unique=False)
    op.create_index(op.f('ix_player_rankings_rank'), 'player_rankings', ['rank'], unique=False)
    op.create_index(op.f('ix_player_rankings_twitter_handle'), 'player_rankings', ['twitter_handle'], unique=False)
    op.create_table('losers_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.Column('team1_id', sa.Integer(), nullable=True),
    sa.Column('team2_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('next_match_id', sa.Integer(), nullable=True),
    sa.Column('dropped_from_match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dropped_from_match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['next_match_id'], ['losers_matches.id'], ),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'round', 'match_number', name='unique_losers_match_number_per_round')
    )
    op.create_index(op.f('ix_losers_matches_id'), 'losers_matches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_losers_matches_id'), table_name='losers_matches')
    op.drop_table('losers_matches')
    op.drop_index(op.f('ix_player_rankings_twitter_handle'), table_name='player_rankings')
    op.drop_index(op.f('ix_player_rankings_rank'), table_name='player_rankings')
    op.drop_index(op.f('ix_player_rankings_player_name'), table_name='player_rankings')
    op.drop_index(op.f('ix_player_rankings_id'), table_name='player_rankings')
    op.drop_table('player_rankings')
    # ### end Alembic commands ###
