"""Add payment fields to tournaments

Revision ID: 3a5915fa065b
Revises: 8418800f28ad
Create Date: 2025-09-07 09:20:20.242397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5915fa065b'
down_revision = '8418800f28ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('payment_methods', sa.Text(), nullable=True))
    op.add_column('tournaments', sa.Column('payment_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'payment_instructions')
    op.drop_column('tournaments', 'payment_methods')
    # ### end Alembic commands ###