# alembic/versions/44d8da238e77_add_payment_fields_to_tournaments_table.py
"""Add payment fields to tournaments table

Revision ID: 44d8da238e77
Revises: 3a5915fa065b
Create Date: 2025-09-07 10:20:20.965719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d8da238e77'
down_revision = '3a5915fa065b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CORRECTED: Only add payment_details, keep payment_methods
    # Don't add payment_method since we're using payment_methods (plural)
    op.add_column('tournaments', sa.Column('payment_details', sa.String(), nullable=True))
    
    # REMOVED: Don't drop payment_methods - it's already there and working
    # REMOVED: Don't add payment_method - we're using payment_methods instead
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'payment_details')
    # REMOVED: Don't add back payment_methods since we're keeping it
    # REMOVED: Don't drop payment_method since we're not adding it
    # ### end Alembic commands ###