"""Refining match model

Revision ID: 49e074787ec5
Revises: dde5a01a3c65
Create Date: 2024-10-23 09:01:31.607865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e074787ec5'
down_revision: Union[str, None] = 'dde5a01a3c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_rankings_id', table_name='player_rankings')
    op.drop_index('ix_player_rankings_player_name', table_name='player_rankings')
    op.drop_index('ix_player_rankings_rank', table_name='player_rankings')
    op.drop_index('ix_player_rankings_twitter_handle', table_name='player_rankings')
    op.drop_table('player_rankings')
    op.create_index(op.f('ix_matches_match_number'), 'matches', ['match_number'], unique=False)
    op.drop_column('matches', 'bracket_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('bracket_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_matches_match_number'), table_name='matches')
    op.create_table('player_rankings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('twitter_handle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_rankings_pkey')
    )
    op.create_index('ix_player_rankings_twitter_handle', 'player_rankings', ['twitter_handle'], unique=False)
    op.create_index('ix_player_rankings_rank', 'player_rankings', ['rank'], unique=False)
    op.create_index('ix_player_rankings_player_name', 'player_rankings', ['player_name'], unique=False)
    op.create_index('ix_player_rankings_id', 'player_rankings', ['id'], unique=False)
    # ### end Alembic commands ###
