"""Add LeaderboardEntry model and relationships

Revision ID: 5f25b4b3ef02
Revises: 8357ee2bea77
Create Date: 2024-10-09 20:29:22.731898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f25b4b3ef02'
down_revision: Union[str, None] = '8357ee2bea77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
