"""Add team creator tracking for submit scores feature

Revision ID: 6316b509cc5e
Revises: 44d8da238e77
Create Date: 2025-09-09 09:36:12.839665

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '6316b509cc5e'
down_revision = '44d8da238e77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add creator_id column
    op.add_column('teams', sa.Column('creator_id', sa.Integer(), nullable=True))
    
    # Add timestamp columns with proper defaults
    op.add_column('teams', sa.Column('created_at', sa.DateTime(), nullable=True, default=sa.func.now()))
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(), nullable=True, default=sa.func.now()))
    
    # Create foreign key constraint with proper naming
    op.create_foreign_key('fk_teams_creator_id', 'teams', 'users', ['creator_id'], ['id'])
    
    # Create index for better query performance
    op.create_index('ix_teams_creator_id', 'teams', ['creator_id'])
    
    # Update existing teams to set timestamp values
    op.execute("UPDATE teams SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE teams SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop index
    op.drop_index('ix_teams_creator_id', 'teams')
    
    # Drop foreign key constraint
    op.drop_constraint('fk_teams_creator_id', 'teams', type_='foreignkey')
    
    # Drop columns
    op.drop_column('teams', 'updated_at')
    op.drop_column('teams', 'created_at') 
    op.drop_column('teams', 'creator_id')
    
    # ### end Alembic commands ###