# Updated migration file with fixes
"""add tkr

Revision ID: 69af09e2f0f9
Revises: afc65501a784
Create Date: 2025-09-03 09:37:35.792706

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '69af09e2f0f9'
down_revision = 'afc65501a784'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tkr_tournament_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('map_name', sa.String(), nullable=False),
    sa.Column('team_size', sa.Enum('SOLO', 'DUOS', 'TRIOS', 'QUADS', name='tkrteamsize'), nullable=False),
    sa.Column('consecutive_hours', sa.Integer(), nullable=False),
    sa.Column('tournament_days', sa.Integer(), nullable=False),
    sa.Column('best_games_count', sa.Integer(), nullable=False),
    sa.Column('placement_multipliers', sa.JSON(), nullable=False),
    sa.Column('bonus_point_thresholds', sa.JSON(), nullable=True),
    sa.Column('max_points_per_map', sa.Integer(), nullable=True),
    sa.Column('host_percentage', sa.Float(), nullable=True, default=0.0),  # Add default
    sa.Column('show_prize_pool', sa.Boolean(), nullable=True, default=True),  # Add default
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id')
    )
    op.create_index(op.f('ix_tkr_tournament_configs_id'), 'tkr_tournament_configs', ['id'], unique=False)
    
    op.create_table('tkr_team_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('team_rank', sa.Integer(), nullable=False),
    sa.Column('players', sa.JSON(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_rerunning', sa.Boolean(), nullable=True, default=False),  # Add default
    sa.Column('using_free_entry', sa.Boolean(), nullable=True, default=False),  # Add default
    sa.Column('free_entry_players', sa.JSON(), nullable=True),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIAL', 'PAID_FULL', 'FREE_ENTRY', name='paymentstatus'), nullable=True, default='UNPAID'),  # Add default
    sa.Column('payment_amount', sa.Float(), nullable=True, default=0.0),  # Add default
    sa.Column('paid_to', sa.String(), nullable=True),
    sa.Column('payment_notes', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True, default=datetime.utcnow),  # Add default
    sa.Column('updated_at', sa.DateTime(), nullable=True, default=datetime.utcnow),  # Add default
    sa.ForeignKeyConstraint(['config_id'], ['tkr_tournament_configs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tkr_team_registrations_id'), 'tkr_team_registrations', ['id'], unique=False)
    
    op.create_table('tkr_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('map_name', sa.String(), nullable=False),
    sa.Column('team_size', sa.Enum('SOLO', 'DUOS', 'TRIOS', 'QUADS', name='tkrteamsize'), nullable=False),
    sa.Column('consecutive_hours', sa.Integer(), nullable=False),
    sa.Column('tournament_days', sa.Integer(), nullable=False),
    sa.Column('best_games_count', sa.Integer(), nullable=False),
    sa.Column('placement_multipliers', sa.JSON(), nullable=False),
    sa.Column('bonus_point_thresholds', sa.JSON(), nullable=True),
    sa.Column('max_points_per_map', sa.Integer(), nullable=True),
    sa.Column('host_percentage', sa.Float(), nullable=True, default=0.0),  # Add default
    sa.Column('show_prize_pool', sa.Boolean(), nullable=True, default=True),  # Add default
    sa.Column('source_config_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.utcnow),  # Add default
    sa.Column('updated_at', sa.DateTime(), nullable=True, default=datetime.utcnow),  # Add default
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_config_id'], ['tkr_tournament_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tkr_templates_id'), 'tkr_templates', ['id'], unique=False)
    
    op.create_table('tkr_game_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_registration_id', sa.Integer(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.Column('vod_url', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('base_score', sa.Float(), nullable=True),
    sa.Column('bonus_points', sa.Float(), nullable=True, default=0.0),  # Add default
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='submissionstatus'), nullable=True, default='PENDING'),  # Add default
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, default=datetime.utcnow),  # Add default
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_registration_id'], ['tkr_team_registrations.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tkr_game_submissions_id'), 'tkr_game_submissions', ['id'], unique=False)
    
    op.create_table('tkr_leaderboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_registration_id', sa.Integer(), nullable=False),
    sa.Column('total_kills', sa.Integer(), nullable=True, default=0),  # Add default
    sa.Column('total_score', sa.Float(), nullable=True, default=0.0),  # Add default
    sa.Column('games_submitted', sa.Integer(), nullable=True, default=0),  # Add default
    sa.Column('current_rank', sa.Integer(), nullable=True),
    sa.Column('average_kills', sa.Float(), nullable=True),
    sa.Column('average_placement', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True, default=datetime.utcnow),  # Add default
    sa.ForeignKeyConstraint(['team_registration_id'], ['tkr_team_registrations.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tkr_leaderboards_id'), 'tkr_leaderboards', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tkr_leaderboards_id'), table_name='tkr_leaderboards')
    op.drop_table('tkr_leaderboards')
    op.drop_index(op.f('ix_tkr_game_submissions_id'), table_name='tkr_game_submissions')
    op.drop_table('tkr_game_submissions')
    op.drop_index(op.f('ix_tkr_templates_id'), table_name='tkr_templates')
    op.drop_table('tkr_templates')
    op.drop_index(op.f('ix_tkr_team_registrations_id'), table_name='tkr_team_registrations')
    op.drop_table('tkr_team_registrations')
    op.drop_index(op.f('ix_tkr_tournament_configs_id'), table_name='tkr_tournament_configs')
    op.drop_table('tkr_tournament_configs')
    # ### end Alembic commands ###