"""update losers match model

Revision ID: 6f863f8af0f5
Revises: 35d77a76c071
Create Date: 2024-12-16 14:30:52.300082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f863f8af0f5'
down_revision: Union[str, None] = '35d77a76c071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('losers_matches', sa.Column('team1_from_winners', sa.Boolean(), nullable=True))
    op.add_column('losers_matches', sa.Column('team1_winners_round', sa.Integer(), nullable=True))
    op.add_column('losers_matches', sa.Column('team1_winners_match_number', sa.Integer(), nullable=True))
    op.add_column('losers_matches', sa.Column('team2_from_winners', sa.Boolean(), nullable=True))
    op.add_column('losers_matches', sa.Column('team2_winners_round', sa.Integer(), nullable=True))
    op.add_column('losers_matches', sa.Column('team2_winners_match_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('losers_matches', 'team2_winners_match_number')
    op.drop_column('losers_matches', 'team2_winners_round')
    op.drop_column('losers_matches', 'team2_from_winners')
    op.drop_column('losers_matches', 'team1_winners_match_number')
    op.drop_column('losers_matches', 'team1_winners_round')
    op.drop_column('losers_matches', 'team1_from_winners')
    # ### end Alembic commands ###
