"""Update tournament enum values

Revision ID: 7289dc1cb135
Revises: 6186b1406623
Create Date: 2024-10-21 11:36:09.443438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7289dc1cb135'
down_revision: Union[str, None] = '6186b1406623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_rankings_id', table_name='player_rankings')
    op.drop_index('ix_player_rankings_player_name', table_name='player_rankings')
    op.drop_index('ix_player_rankings_rank', table_name='player_rankings')
    op.drop_index('ix_player_rankings_twitter_handle', table_name='player_rankings')
    op.drop_table('player_rankings')
    op.alter_column('tournaments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ONGOING', 'COMPLETED', 'CANCELLED', name='tournamentstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ONGOING', 'COMPLETED', 'CANCELLED', name='tournamentstatus'),
               nullable=False)
    op.create_table('player_rankings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('twitter_handle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_rankings_pkey')
    )
    op.create_index('ix_player_rankings_twitter_handle', 'player_rankings', ['twitter_handle'], unique=False)
    op.create_index('ix_player_rankings_rank', 'player_rankings', ['rank'], unique=False)
    op.create_index('ix_player_rankings_player_name', 'player_rankings', ['player_name'], unique=False)
    op.create_index('ix_player_rankings_id', 'player_rankings', ['id'], unique=False)
    # ### end Alembic commands ###
