"""added description and rules to tournament

Revision ID: 7e8595d87622
Revises: ba349821d372
Create Date: 2025-01-02 08:32:30.445953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8595d87622'
down_revision: Union[str, None] = 'ba349821d372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('rules', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'rules')
    op.drop_column('tournaments', 'description')
    # ### end Alembic commands ###
