# alembic/script.py.mako
"""add end time

Revision ID: afc65501a784
Revises: 0553481d0d59
Create Date: 2025-08-29 11:59:08.308272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc65501a784'
down_revision = '0553481d0d59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('end_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'end_time')
    # ### end Alembic commands ###