"""update for new WinnersBracket

Revision ID: ba349821d372
Revises: 6f863f8af0f5
Create Date: 2024-12-20 08:11:37.829690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba349821d372'
down_revision: Union[str, None] = '6f863f8af0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('bracket_position', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('has_bye', sa.Boolean(), nullable=True))
    op.add_column('matches', sa.Column('round_name', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('tournaments', sa.Column('bracket_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'bracket_config')
    op.drop_column('matches', 'is_completed')
    op.drop_column('matches', 'round_name')
    op.drop_column('matches', 'has_bye')
    op.drop_column('matches', 'bracket_position')
    # ### end Alembic commands ###
