# alembic/script.py.mako
"""add_logo_fields_to_host_profiles

Revision ID: bb55f860fcf8
Revises: c295ba9e7727
Create Date: 2025-08-27 11:43:04.868659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb55f860fcf8'
down_revision = 'c295ba9e7727'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_profiles', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('host_profiles', sa.Column('logo_public_id', sa.String(), nullable=True))
    op.add_column('host_profiles', sa.Column('organization_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host_profiles', 'organization_name')
    op.drop_column('host_profiles', 'logo_public_id')
    op.drop_column('host_profiles', 'logo_url')
    # ### end Alembic commands ###