# alembic/script.py.mako
"""add host applications

Revision ID: c295ba9e7727
Revises: 0a79e334c3bb
Create Date: 2025-02-02 23:25:24.267909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c295ba9e7727'
down_revision = '0a79e334c3bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###