"""Remove match columns and add seed column to team

Revision ID: dde5a01a3c65
Revises: cc1499c4c0e4
Create Date: 2024-10-23 08:11:05.656545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde5a01a3c65'
down_revision: Union[str, None] = 'cc1499c4c0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_rankings_id', table_name='player_rankings')
    op.drop_index('ix_player_rankings_player_name', table_name='player_rankings')
    op.drop_index('ix_player_rankings_rank', table_name='player_rankings')
    op.drop_index('ix_player_rankings_twitter_handle', table_name='player_rankings')
    op.drop_table('player_rankings')
    op.drop_column('matches', 'team2_seed')
    op.drop_column('matches', 'team1_seed')
    op.drop_column('matches', 'is_upper_bracket')
    op.add_column('teams', sa.Column('seed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'seed')
    op.add_column('matches', sa.Column('is_upper_bracket', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('team1_seed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('team2_seed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('player_rankings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('twitter_handle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_rankings_pkey')
    )
    op.create_index('ix_player_rankings_twitter_handle', 'player_rankings', ['twitter_handle'], unique=False)
    op.create_index('ix_player_rankings_rank', 'player_rankings', ['rank'], unique=False)
    op.create_index('ix_player_rankings_player_name', 'player_rankings', ['player_name'], unique=False)
    op.create_index('ix_player_rankings_id', 'player_rankings', ['id'], unique=False)
    # ### end Alembic commands ###
