# alembic/script.py.mako
"""add activity and system health

Revision ID: ebaed7ad28d6
Revises: ad7bdd8b68f4
Create Date: 2025-01-07 01:37:15.014016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebaed7ad28d6'
down_revision = 'ad7bdd8b68f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###