# alembic/script.py.mako
"""add activities relationship to user

Revision ID: ee5a6df92089
Revises: ebaed7ad28d6
Create Date: 2025-01-07 01:47:05.164526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5a6df92089'
down_revision = 'ebaed7ad28d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###