"""Refining match model so match number resets 2

Revision ID: eecbaac6df6a
Revises: 6684e32e6e2f
Create Date: 2024-10-23 09:17:15.008120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecbaac6df6a'
down_revision: Union[str, None] = '6684e32e6e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_rankings_id', table_name='player_rankings')
    op.drop_index('ix_player_rankings_player_name', table_name='player_rankings')
    op.drop_index('ix_player_rankings_rank', table_name='player_rankings')
    op.drop_index('ix_player_rankings_twitter_handle', table_name='player_rankings')
    op.drop_table('player_rankings')
    op.add_column('matches', sa.Column('bracket_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'bracket_position')
    op.create_table('player_rankings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('twitter_handle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_rankings_pkey')
    )
    op.create_index('ix_player_rankings_twitter_handle', 'player_rankings', ['twitter_handle'], unique=False)
    op.create_index('ix_player_rankings_rank', 'player_rankings', ['rank'], unique=False)
    op.create_index('ix_player_rankings_player_name', 'player_rankings', ['player_name'], unique=False)
    op.create_index('ix_player_rankings_id', 'player_rankings', ['id'], unique=False)
    # ### end Alembic commands ###
